#! /bin/sh

#
# BSPWM CONFIG
#

#
# Rice variables
#
read -r RICE_THEME < $HOME/.config/bspwm/.rice
export RICE_THEME

PATH="$HOME/.config/bspwm/scripts:$PATH"

rice_dir="$HOME/.config/bspwm/rices/$RICE_THEME"

#
# Fix Java Applications
#

export _JAVA_AWT_WM_NONREPARENTING=1

# 
# BSPWM RULES
#

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# 
# Rice Launching
#

proccesses=("picom" "polybar" "sxhkd" "dunst" "clipit")

for proccess in "${proccesses[@]}"; do 
  killall -q $proccess; sleep 0.1
done

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# $HOME/.config/polybar/launch.sh 
# polybar -q example -c $rice_dir/config
. $rice_dir/Theme.sh

# Wallpaper
$HOME/.config/bspwm/scripts/WallpaperManager --init
#feh --no-fehbg --bg-fill $(cat ~/.wallpaper) &

# Network Manger Applet
nm-applet &

# Bluetooth Applet
blueman-applet &

# Clipboard Manager
# killall -q clipit
clipit &

# Composite Manger
picom & # --config $HOME/.config/picom/ &

# Notification Daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Keyboard Layout
setxkbmap -layout latam

# Fix cursor
xsetroot -cursor_name left_ptr
