#! /bin/sh

#
# BSPWM CONFIG
#

#
# Rice variables
#
read -r RICE_THEME < $HOME/.config/bspwm/.rice
export RICE_THEME

PATH="$HOME/.config/bspwm/scripts:$PATH"

rice_dir="$HOME/.config/bspwm/rices/$RICE_THEME"

#
# Fix Java Applications
#

export _JAVA_AWT_WM_NONREPARENTING=1

# 
# BSPWM RULES
#

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# BSPWM COLORS
#
 
fibspc config normal_border_color "#033382"
bspc config active_border_color "#46bfee"
bspc config focused_border_color "#8f69c2"
bspc config presel_feedback_color "#00a832"

# Follow pointer
# bspc config focus_follows_pointer true

#
# WORKSPACES
#

#workspaces() {
#	name=1
#	for monitor in $(bspc query -M); do
#		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
#		(( name++ ))
#	done
#}

#workspaces

# 
# Rice Launching
#

proccesses=("picom" "polybar" "sxhkd" "dunst" "clipit")

for proccess in "${proccesses[@]}"; do 
  killall -q $proccess; sleep 0.1
done

sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Launching rice
. $rice_dir/Theme.sh

# Wallpaper
WallpaperManager --init

# Network Manger Applet
nm-applet &

# Bluetooth Applet
blueman-applet &

# Clipboard Manager
clipit &

# Composite Manger
picom & # --config $HOME/.config/picom/ &

# Notification Daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Keyboard Layout
setxkbmap -layout latam

# Fix cursor
xsetroot -cursor_name left_ptr

# Enable touchpad one touch clic
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
