#!/bin/bash


rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="  Shutdown"
reboot="  Restart"
lock="󰌾  Lock"
suspend="󰤄  Sleep"
logout="󰍃 Logout"

# Variable passed to rofi
# options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"
options="$shutdown\n$reboot\n$logout\n$lock\n$suspend"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        i3lock-fancy
        ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        loginctl terminate-user $USER
        ;;
esac
