#!/bin/bash

read -r riceSel < $HOME/.config/bspwm/.rice

CONFIG_FILE="$HOME/.config/wallpaper.conf"


selector_without_preview(){
  # Poner tema al selector
  rofi_command="rofi -theme $HOME/.config/bspwm/assets/themes/wallpaperSelector.rasi"

  # Obtener la ruta de la carpeta que contiene las imágenes
  folder="$HOME/Imágenes/Wallpapers"

  # Obtener la lista de imágenes en la carpeta
  files=$(find "$folder" -type f -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" | sort)

  # Formatear la lista de imágenes para mostrar solo los nombres de archivo y su directorio padre
  formatted_files=$(echo "$files" | xargs -n 1 bash -c 'echo "$(basename "$(dirname "$0")")/$(basename "$0")"')

  # Mostrar la lista de imágenes en un menú rofi y capturar la selección del usuario
  choice=$(echo "$formatted_files" | $rofi_command -dmenu -i -mesg "Seleccione una imagen:" -format d)
  
  # Obtener la ruta completa de la imagen seleccionada
  selected_file=$(echo "$files" | sed -n "$choice"p)
}


selector_with_preview(){
  # Poner tema al selector
  rofiConfig="$HOME/.config/bspwm/assets/themes/themeselect.rasi"

  # Obtener la ruta de la carpeta que contiene las imágenes
  folder="$HOME/.config/bspwm/rices/$riceSel/walls"

  # Obtener la lista de imágenes en la carpeta (sin incluir subcarpetas)
  files=$(ls "$folder" | grep -E '\.jpg$|\.jpeg$|\.png$' | sort)

  # Mostrar la lista de imágenes en un menú rofi y capturar la selección del usuario
  choice=$(echo "$files" | while read -r rfile; do
      echo -en "$rfile\x00icon\x1f$folder/$rfile\n"
  done | rofi -dmenu -i -mesg "Seleccione una imagen:" -format d -config "$rofiConfig")

  selected_file="$folder/$(echo "$files" | sed -n "$choice"p)"
}

set_wallpaper(){
  # Si el usuario selecciona una imagen, establecerla como fondo de pantalla
  if [ -n "$choice" ]; then
    sed -i "s|^ruta=.*|ruta=$selected_file|" "$CONFIG_FILE"
    feh --no-fehbg --bg-fill "$selected_file"
    #echo "$selected_file" > ~/.wallpaper
  fi
}

help_command(){
  echo -e "Uso WallpaperSwitcher [opcion]
  Opciones:
  --simple: Despliega el selector de fondo con solo texto\n
  --fancy: Despliega el selector de fondo con miniaturas\n
  --help: Muestra esta pagina de ayuda\n"
}


# Modos del script
case "$1" in
  --simple) 
    selector_without_preview
    set_wallpaper
  ;;
  --fancy) 
    selector_with_preview
    set_wallpaper
  ;;
  --help | *)
    help_command
  ;;
esac

exit 0
