#!/bin/bash

# Comando de ayuda
help_command(){
  echo -e "Uso WallpaperManager [opcion]
  Opciones:
  --help: Muestra esta pagina de ayuda\n
  --browser: Abre el navegador\n
  --riceselector: Abre el selector de temas\n
  --messages: Abre la aplicacion de mensajeria\n
  --music: Abre el reproductor de musica\n"
}

case "$1" in
  --browser)
    firefox
  ;;
  --riceselector)
    RiceSelector
  ;;
  --messages)
    ferdium
  ;;
  --music)
    vlc
  ;;
  --terminal)
    kitty -d ~
  ;;
  --help|*)
    help_command
  ;;
esac

exit 0
