#!/usr/bin/env bash

## Fix Java Applications
export _JAVA_AWT_WM_NONREPARENTING=1

## Network Manger Applet
nm-applet &

## Bluetooth Applet
blueman-applet &

## Clipboard Manager
killall -q clipit
clipit &

## Composite Manger
picom &

## Wallpaper
feh --bg-fill $(cat ~/.wallpaper) &

## Keyboard Layout
setxkbmap -layout latam
