#!/bin/bash

read -r riceSel < $HOME/.config/bspwm/.rice

CONFIG_FILE="$HOME/wallpaper.conf"

rofiConfig="$HOME/.config/bspwm/scripts/themes/themeselect.rasi"

# Obtener la ruta de la carpeta que contiene las imágenes
folder="$HOME/.config/bspwm/rices/$riceSel/walls"

# Obtener la lista de imágenes en la carpeta (sin incluir subcarpetas)
files=$(ls "$folder" | grep -E '\.jpg$|\.jpeg$|\.png$' | sort)

# Mostrar la lista de imágenes en un menú rofi y capturar la selección del usuario
rofiSel=$(echo "$files" | while read -r rfile; do
    echo -en "$rfile\x00icon\x1f$folder/$rfile\n"
done | rofi -dmenu -i -mesg "Seleccione una imagen:" -format d -config "$rofiConfig")

choice="$folder/$(echo "$files" | sed -n "$rofiSel"p)"

# Si el usuario selecciona una imagen, establecerla como fondo de pantalla
if [ -n "$rofiSel" ]; then
    #sed -i "s/^modo=.*/modo=$nuevo_modo/" "$CONFIG_FILE"
    sed -i "s|^ruta=.*|ruta=$choice|" "$CONFIG_FILE"
    feh --no-fehbg --bg-fill "$choice"
    #echo "$choice" >~/.wallpaper
fi

