#!/bin/bash

# Ruta al archivo de configuración
CONFIG_FILE="$HOME/wallpaper.conf"
MODE=$(grep '^modo=' "$CONFIG_FILE" | cut -d'=' -f2)

rofi_command="rofi -theme $HOME/.config/bspwm/scripts/themes/powermenu.rasi"
# Función para mostrar el menú de selección de modo
seleccionar_modo() {
  modo=$(echo -e "estatico\naleatorio\nanimado" | $rofi_command -p "Modo Actual: $MODE" -dmenu)

  if [ -n "$modo" ]; then
    MODE=$modo
    # Actualiza el modo en el archivo de configuración
    sed -i "s/^modo=.*/modo=$modo/" "$CONFIG_FILE"

    $HOME/.config/bspwm/scripts/wallManager
  fi
}

cambiar_fondo(){
  case "$MODE" in
    "aleatorio")
      feh -z --no-fehbg --bg-fill $HOME/.config/bspwm/rices/$RICE_THEME/walls &
    ;;
    "estatico")
      $HOME/.config/bspwm/scripts/wallpaperSelect
    ;;
    "animado")
      notify-send -u normal -i ~/.config/bspwm/scripts/assets/a.png -a WallModeSwitcher -t 1000 "Not Implemented yet"
    ;;
    *)
    ;;
  esac
}

case "$1" in
  --selector) seleccionar_modo
  ;;
  --update) cambiar_fondo
  ;;
  *)
  ;;
esac

exit 0
